// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvszgtpjyxfgslcghiwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2c3pndHBqeXhmZ3NsY2doaXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTk1NTAsImV4cCI6MjA2MzU3NTU1MH0.nqMQJRt1HsTt8c1cIueQJpUz7sHGHUJ9rgiOCwJVztE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);